### ISSUE TITLE
pubdev_docker Replace Issues

### ISSUE THREAD

**Issue by nilswindisch** [subugoe/goefis#56]
The replace/patch script stumbles over various issues that seem to be not replaceable easily. How to proceed with that?

Output from pubdev_docker dev branch
https://gist.github.com/nilswindisch/50eaa8a9922f8c29632e8fe13d146115

**Comment by dbeucke** [comment]
You mean the warnings?

**Comment by nilswindisch** [comment]
yes

**Comment by christianmahnke** [comment]
These can be ignored by now, I thought it might be a good idea to have an overview about missing strings. This could be assigned to Daniel to decide on suitable replacements.

@dbeucke: Consider to change the title of this issue to something like "Keep track of strings to be changed", since this is an ongoing task. With release 0.1.0 there have been more changes, add change proposals here. Add it to a milestone.

**Comment by christianmahnke** [comment]
This is now done as #68.
